FROM arm64v8/ubuntu:20.04

COPY qemu-aarch64-static /usr/bin

RUN apt-get update;\
    apt-get install -y python3 python3-pip python3-dev build-essential git wget xz-utils ninja-build meson flex bison

RUN wget --no-check-certificate https://nodejs.org/download/release/v16.13.0/node-v16.13.0-linux-arm64.tar.xz;\
    tar xvJf node-v16.13.0-linux-arm64.tar.xz;\
    rm node-v16.13.0-linux-arm64.tar.xz

ENV PATH "/node-v16.13.0-linux-arm64/bin:$PATH"

CMD ["bash"]